#!/usr/bin/python3
def raise_exception_msg(outcome=""):
    raise NameError(outcome)
